### ISSUE TITLE
Strange behaviour during launching bblfsh server

### ISSUE THREAD

**Issue by EgorBu** [bblfsh/server#37]
When you launch bblfsh server and send requests to extract UAST before it fetches all docker images, bblfsh server returns empty responses.

How to reproduce:
1) launch server
`docker run --privileged -p 9432:9432 --name bblfsh -e BBLFSH_MAX_INSTANCES_PER_DRIVER=1 bblfsh/server`
2) in parallel console start to send requests:
`LC_ALL=en_GB.UTF-8 python3 -m ast2vec repo2coocc --bblfsh 172.17.0.1:9432  -r https
://github.com/some/repo --linguist ./enry -o test_uast_one/repo.asdf`
then you can check response:
`python3 -m ast2vec dump test_uast_one/repo.asdf`
and result is 
```
{'created_at': datetime.datetime(2017, 6, 20, 14, 29, 7, 781788),
 'dependencies': [],
 'model': 'co-occurrences',
 'uuid': 'f582e9a1-bcdb-4acd-9979-aa0ecf5d1f4f',
 'version': [1, 0, 0]}
Number of words: 0
First 10 words: []
Matrix info: number of non zero elements 0 , shape: [0, 0]
```
but if you wait and send request after loading of all images:
```
{'created_at': datetime.datetime(2017, 6, 20, 14, 31, 13, 988607),
 'dependencies': [],
 'model': 'co-occurrences',
 'uuid': '6da8f27b-7769-447b-93eb-afdfc4adfa5e',
 'version': [1, 0, 0]}
Number of words: 74
First 10 words: ['print', 'input', 'file', 'output', 'reader', 'writer', 'header', 'line', 'csv', 'sys']
Matrix info: number of non zero elements 2435 , shape: [74, 74]
```

**Comment by abeaumont** [comment]
@EgorBu where can I get that ast2vec module and which version are you using to reproduce the problem?

**Comment by EgorBu** [comment]
github.com/src-d/ast2vec
I think the lastest version should be okay

**Comment by abeaumont** [comment]
@EgorBu the problem seems related with `parse_uast` timeout parameter in python client. Try with https://github.com/bblfsh/client-python/pull/4 adjusting the timeout, I guess that should fix the problem.

**Comment by vmarkovtsev** [comment]
@EgorBu We need to verify this tomorrow.
