### ISSUE TITLE
Returned value when a language can't be detected

### ISSUE THREAD

**Issue by mcarmonaa** [bblfsh/server#63]
this is the code used in language.go
```go
func GetLanguage(filename string, content []byte) string {
	lang := enry.GetLanguage(filename, content)
	if lang == "" {
		lang = enry.OtherLanguage
	}

	lang = strings.ToLower(lang)
	lang = strings.Replace(lang, " ", "-", -1)
	lang = strings.Replace(lang, "+", "p", -1)
	lang = strings.Replace(lang, "#", "sharp", -1)
	return lang
}

```

but since enry.OtherLanguage was changed to be the string zero value `""`, the if statement is reassigning again the same value to lang.

What is the expected value this function should return in case a language couldn't be detected?

**Comment by abeaumont** [comment]
I think current implementation is correct, except that it probably should directly return `enry.OtherLanguage` directly in the `if`. The fact that  currently `enry.OtherLanguage` is `""` is something that `server` developers should not care about.

**Comment by mcarmonaa** [comment]
`enry.GetLanguage` doesn't return `""` if it can't detect any language, it returns `enry.OtherLanguage`, so the code should something like:

```go
lang := enry.GetLanguage(filename, content)
if lang == enry.OtherLanguage {
        return lang
}
```

Is it ok? I could make a PR to fix it.

**Comment by abeaumont** [comment]
Oh, I see. If you could do the PR that would be great.

**Comment by mcarmonaa** [comment]
https://github.com/bblfsh/server/pull/64
