### ISSUE TITLE
Docker: allow passing CLI args to bblfsh server binary

### ISSUE THREAD

**Issue by bzz** [bblfsh/server#69]
Right now

`docker run --privileged -p 9432:9432 --name bblfsh bblfsh/server --some-option 1`

would not pass CLI arguments to the server binary.

This could be changed if instead of `CMD` an `ENTRYPOINT` used in [Dockerfile#L5](https://github.com/bblfsh/server/blob/master/Dockerfile#L5)

**Comment by mcarmonaa** [comment]
solved https://github.com/bblfsh/server/pull/71

**Comment by smola** [comment]
Note that you can always pass options by specifying binary to run.
