### ISSUE TITLE
Driver image override inside docker

### ISSUE THREAD

**Issue by bzz** [bblfsh/server#74]
Right now, if one tries to override default driver images while running server in docker container

```
BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f" docker run -e BBLFSH_DRIVER_IMAGES --privileged -p 9432:9432 --name bblfsh bblfsh/server:dev-45a5e8f

time="2017-07-17T09:28:02Z" level=debug msg="binding to 0.0.0.0:9432"
time="2017-07-17T09:28:02Z" level=debug msg="initializing runtime at /tmp/bblfsh-runtime"
time="2017-07-17T09:28:02Z" level=debug msg="Overriding image for python: docker-daemon:bblfsh/python-driver:dev-4dd607b"
time="2017-07-17T09:28:02Z" level=debug msg="Overriding image for java: docker-daemon:bblfsh/java-driver:dev-45a5e8f"
time="2017-07-17T09:28:02Z" level=debug msg="starting server"
time="2017-07-17T09:28:02Z" level=debug msg="registering gRPC service"
time="2017-07-17T09:28:02Z" level=info msg="starting gRPC server"
```

The client will fail with

```
error getting driver: missing driver for language python: runtime failure: Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

error getting driver: missing driver for language java: runtime failure: Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
```

There are no attempts to fetch a driver in server logs

```
```

**Comment by bzz** [comment]
Actually, on linux if I try

```
BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f" ./build/bblfsh server  --transport=docker-daemon
```

I get very similar

```
[error getting driver: missing driver for language java: runtime failure: Error loading image from docker engine: Error response from daemon: reference does not exist
```

**Comment by mcarmonaa** [comment]
@bzz I can't reproduce the last error you get in Linux

```bash
➜  build git:(master) BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f" bblfsh server  --transport=docker-daemon 

DEBU[0000] binding to 0.0.0.0:9432                      
DEBU[0000] initializing runtime at /tmp/bblfsh-runtime  
DEBU[0000] Overriding image for python: docker-daemon:bblfsh/python-driver:dev-4dd607b 
DEBU[0000] Overriding image for java: docker-daemon:bblfsh/java-driver:dev-45a5e8f 
DEBU[0000] setting maximum size for sending and receiving messages to 104857600 
DEBU[0000] starting server                              
DEBU[0000] registering gRPC service                     
INFO[0000] starting gRPC server                         

```

**Comment by bzz** [comment]
The error I reported happens not on the server startup, but when a client actually processes files.

**Comment by abeaumont** [comment]
As commented offline, I think the problem is related with the transport used. `docker-daemon` transport looks for local images available through docker daemon (built locally), while you may expect them to get retrieved from the registry. You need to use `docker` transport for that. Please confirm if that's the problem and if so, we should fix and clearify the documentation.

**Comment by mcarmonaa** [comment]
In the other hand, `--transport=docker-daemon` is not needed since it doesn't override the transport specified for images in BBLFSH_DRIVER_IMAGES

**Comment by bzz** [comment]
That is what I tried on non-linux - make sure no Driver images exist and then

```
docker pull bblfsh/java-driver:dev-45a5e8f
docker pull bblfsh/python-driver:dev-4dd607b

BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f" docker run -e BBLFSH_DRIVER_IMAGES --privileged -p 9432:9432 --name bblfsh bblfsh/server:dev-6bc7fd7 --max-message-size=100
```

The result was the same - empty server logs (no requests from clients) and 

```
[error getting driver: missing driver for language java: runtime failure: Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
```

**Comment by abeaumont** [comment]
Ok, running the above commands on linux I get the following client error:

````
> bblfsh client t.java
DEBU[0000] reading file: t.java                         
DEBU[0000] setting maximum size for sending and receiving messages to 104857600 
DEBU[0000] dialing server at localhost:9432             
DEBU[0000] instantiating service client                 
DEBU[0000] sending request                              
Status:  fatal
Errors: 
 .  error getting driver: missing driver for language java: runtime failure: Error loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
INFO[0000] exiting without error                        
```

**Comment by mcarmonaa** [comment]
@abeaumont  @bzz I have the same error running a server in a container, but It's not related to overriding with BBLFH_DRIVER_IMAGES varibale, if you run `docker run -e BBLFSH_DRIVER_IMAGES --privileged -p 9432:9432 --name bblfsh bblfsh/server:dev-6bc7fd7 --transport=docker-daemon ` you will get the same error.

I think it's produced because drivers are containers launched from the server container, but the server container can't see the local docker-daemon, in the end a container is isolated.

**Comment by abeaumont** [comment]
@mcarmonaa I think you're right, that would mean that it doesn't make sense to use the `docker-daemon` transport. @smola is this correct?

**Comment by juanjux** [comment]
Yes, I can reproduce this, my theory is that the server is looking for the image on the local docker daemon inside it's own docker image and not on the hosting one because the `--docker-transport` option works perfectly with the server running outside docker.

**Comment by juanjux** [comment]
After much code reading and messing around, there is not a programmatic solution  that I know because the server inside the Docker will search for the Docker daemon that it can access, inside it's own container, but there is a very simple solution that works and it's sharing the `/var/run/docker.sock` Unix socket with the container:

```bash
BBLFSH_DRIVER_IMAGES="python=docker-daemon:bblfsh/python-driver:dev-4dd607b;java=docker-daemon:bblfsh/java-driver:dev-45a5e8f" docker run -e BBLFSH_DRIVER_IMAGES  -v /var/run/docker.sock:/var/run/docker.sock --privileged -p 9432:9432 --name bblfsh bblfsh/server:dev-45a5e8f
```

I'll modify the server documentation to reflect this.

**Comment by juanjux** [comment]
https://github.com/bblfsh/documentation/issues/76

**Comment by abeaumont** [comment]
@juanjux What you propose is what @mcarmonaa already proposed earlier, but according to him, it didn't work. Did you manage to get it working?

**Comment by juanjux** [comment]
Yes, this works for me, both with the environment variable and with the `--transport=docker-daemon` option, but if you use the `transport` option without specifying an image with the env variable it will search for `bblfsh/XXX-driver:latest` so if you don't have an image tagged as latest (with it's not automatic) it won't find any image; I guess that's what happened to @mcarmonaa (@mcarmonaa can you confirm this?).
