### ISSUE TITLE
QUALIFIED_IDENTIFIER is not SIMPLE_IDENTIFIER and duplication of CALL_CALLEE role

### ISSUE THREAD

**Issue by zurk** [bblfsh/server#82]
I found that `QUALIFIED_IDENTIFIER` is not `SIMPLE_IDENTIFIER`, but @vmarkovtsev say that it is supposed to be.
Also, I found duplication of `CALL_CALLEE` role.

How to reproduce: 
```python
from bblfsh.client import BblfshClient

filepath = "./matplotlib_example.py"
bc = BblfshClient("0.0.0.0:9432")
res = bc.parse(filepath, language='Python')
print(res)
```
`matplotlib_example.py`:
```python
from matplotlib import pyplot as plt
plt.figure()
```
Output (lines 76-83):
```
       token: "figure"
        start_position {
          line: 2
          col: 1
        }
        roles: CALL_CALLEE
        roles: CALL_CALLEE
        roles: QUALIFIED_IDENTIFIER
```

The problem is in `figure` token. It means that we do not take into account function names during our machine leaning analysis

**Comment by abeaumont** [comment]
@zurk thanks for reporting. If I understand it correctly, it seems a python specific problem, and thus it should be reported in the [python driver](https://github.com/bblfsh/python-driver/) project.

**Comment by zurk** [comment]
Ok, close this one.
Moved to https://github.com/bblfsh/python-driver/issues/51
