### ISSUE TITLE
Cannot install via go get due to github.com/sirupsen/logrus namespace collision

### ISSUE THREAD

**Issue by rporres** [bblfsh/server#89]
This is related to some internal renaming. See https://github.com/sirupsen/logrus/issues/570#issuecomment-313933276

```
ubuntu@ubuntu16:~$ go version
go version go1.8.3 linux/amd64
ubuntu@ubuntu16:~$ echo $GOPATH
/home/ubuntu/go
ubuntu@ubuntu16:~$ go get -v github.com/bblfsh/server
can't load package: package github.com/bblfsh/server: case-insensitive import collision: "github.com/Sirupsen/logrus" and "github.com/sirupsen/logrus"
```

Apparently logrus should be imported using `github.com/sirupsen/logrus`

**Comment by abeaumont** [comment]
Thanks for reporting @rporres. Installation through `go get` is not supported, since the server handles the dependencies through `glide`.
