### ISSUE TITLE
Smacc

### ISSUE THREAD

**Issue by ShalokShalom** [bblfsh/server#90]
You are maybe interested: https://github.com/ThierryGoubier/SmaCC/issues/25

**Comment by abeaumont** [comment]
@ShalokShalom nices project, it certainly seems it could at least be a candidate to generate ASTs for languages without a AST library. I'll look deeper at both its AST generation framework and its transformation tools which seem pretty interesting too.

Thanks for the pointer!

**Comment by ShalokShalom** [comment]
Sure sure
