### ISSUE TITLE
Client inside a container doesn't work as expected

### ISSUE THREAD

**Issue by abeaumont** [bblfsh/server#96]
According to [documentation](https://doc.bblf.sh/user/getting-started.html#running-with-docker-recommended), this would be enough to make both server and client work with docker:

```
$ docker run --privileged -p 9432:9432 --name bblfsh bblfsh/server
$ docker run -v $(pwd):/work --link bblfsh bblfsh/server bblfsh client --address=bblfsh:9432 /work/sample.py
```

The second command generates an error instead:

```
$ docker run -v $(pwd):/work --link bblfsh bblfsh/server bblfsh client --address=bblfsh:9432 /work/sample.py
time="2017-09-07T10:03:07Z" level=info msg="binding to bblfsh:9432" 
time="2017-09-07T10:03:07Z" level=info msg="initializing runtime at /tmp/bblfsh-runtime" 
listen tcp 172.17.0.2:9432: bind: cannot assign requested address
time="2017-09-07T10:03:07Z" level=error msg="exiting with error: listen tcp 172.17.0.2:9432: bind: cannot assign requested address" 
```

Separating the linking and client execution parts seem to work though, so there may be same race condition there.

Reported by @dpordomingo

**Comment by dpordomingo** [comment]
I don't know if this info will be useful... but it seems that the server container [already has an entrypoint](https://github.com/bblfsh/server/blob/master/Dockerfile#L5)... and when it happens, the run command can not be used that way (as @mcuadros just told me about a similar problem in the dashboard)

**Comment by abeaumont** [comment]
Fixed by #84

**Comment by dpordomingo** [comment]
Fixed by https://github.com/bblfsh/documentation/pull/84
(the #.84 link points to a different project)

**Comment by abeaumont** [comment]
right, fixed link, thanks!
